#!/bin/bash
#SBATCH --ntasks-per-node=1
#SBATCH -A cs433
#SBATCH -q cs433
#SBATCH --gres=gpu:1
#SBATCH --mem=700G
#SBATCH --time=48:00:00
#SBATCH --output=logs/log_%j.log

# Ensure the logs directory exists
mkdir -p logs

# Activate the virtual environment
source /home/finette/VideoStitching/selma/selmaEnv/bin/activate

# Navigate to the directory containing the script
cd /home/finette/VideoStitching/selma

# Execute the script
python /home/finette/VideoStitching/selma/evaluate.py

# Optional: Deactivate the virtual environment
deactivate

